<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Produk;

class GameSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus semua data lama agar tidak double
        \DB::table('products')->delete();

        DB::table('products')->insert([
            [
                'product_name' => 'Mobile Legends',
                'developer' => 'Moonton',
                'release_date' => '2016-07-14',
                'description' => 'Game MOBA mobile paling populer.',
                'category' => 'MOBA',
                'brand' => 'Moonton',
                'digiflazz_id' => 'mlbb',
                'icon_url' => 'mlbbhuhu.jpg',
                'thumbnail_url' => 'mlbb.png',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Free Fire',
                'developer' => 'Garena',
                'release_date' => '2017-12-04',
                'description' => 'Game battle royale ringan dan seru.',
                'category' => 'Battle Royale',
                'brand' => 'Garena',
                'digiflazz_id' => 'freefire',
                'icon_url' => 'freefire.jpg',
                'thumbnail_url' => 'freefire.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'PUBG Mobile',
                'developer' => 'Tencent',
                'release_date' => '2018-03-19',
                'description' => 'Game battle royale realistis.',
                'category' => 'Battle Royale',
                'brand' => 'Tencent',
                'digiflazz_id' => 'pubgm',
                'icon_url' => 'pubgm.jpg',
                'thumbnail_url' => 'pubgm.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Genshin Impact',
                'developer' => 'miHoYo',
                'release_date' => '2020-09-28',
                'description' => 'Open world RPG dengan grafis indah.',
                'category' => 'RPG',
                'brand' => 'miHoYo',
                'digiflazz_id' => 'genshin',
                'icon_url' => 'kleeGenshin.jpeg',
                'thumbnail_url' => 'kleeGenshin.jpeg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Dota 2',
                'developer' => 'Valve',
                'release_date' => '2013-07-09',
                'description' => 'Game MOBA PC legendaris.',
                'category' => 'MOBA',
                'brand' => 'Valve',
                'digiflazz_id' => 'dota2',
                'icon_url' => 'dota2.jpg',
                'thumbnail_url' => 'dota2.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'AOV',
                'developer' => 'Garena',
                'release_date' => '2016-10-14',
                'description' => 'Arena of Valor, MOBA mobile.',
                'category' => 'MOBA',
                'brand' => 'Garena',
                'digiflazz_id' => 'aov',
                'icon_url' => 'aov.png',
                'thumbnail_url' => 'aov.png',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Apex Legends',
                'developer' => 'Respawn',
                'release_date' => '2019-02-04',
                'description' => 'Battle royale futuristik.',
                'category' => 'Battle Royale',
                'brand' => 'EA',
                'digiflazz_id' => 'apex',
                'icon_url' => 'apex.jpg',
                'thumbnail_url' => 'apex.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Brawl Stars',
                'developer' => 'Supercell',
                'release_date' => '2018-12-12',
                'description' => 'Game action 3v3.',
                'category' => 'Action',
                'brand' => 'Supercell',
                'digiflazz_id' => 'brawl',
                'icon_url' => 'brawl.jpeg',
                'thumbnail_url' => 'brawl.jpeg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Clash of Clans',
                'developer' => 'Supercell',
                'release_date' => '2012-08-02',
                'description' => 'Game strategi klasik.',
                'category' => 'Strategy',
                'brand' => 'Supercell',
                'digiflazz_id' => 'coc',
                'icon_url' => 'coc.jpg',
                'thumbnail_url' => 'coc.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Call of Duty Mobile',
                'developer' => 'Activision',
                'release_date' => '2019-10-01',
                'description' => 'COD versi mobile.',
                'category' => 'FPS',
                'brand' => 'Activision',
                'digiflazz_id' => 'cod',
                'icon_url' => 'cod.jpg',
                'thumbnail_url' => 'cod.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'CS:GO',
                'developer' => 'Valve',
                'release_date' => '2012-08-21',
                'description' => 'Counter-Strike: Global Offensive.',
                'category' => 'FPS',
                'brand' => 'Valve',
                'digiflazz_id' => 'csgo',
                'icon_url' => 'cs.jpeg',
                'thumbnail_url' => 'cs.jpeg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'FIFA',
                'developer' => 'EA Sports',
                'release_date' => '1993-12-15',
                'description' => 'Game sepak bola populer.',
                'category' => 'Sports',
                'brand' => 'EA',
                'digiflazz_id' => 'fifa',
                'icon_url' => 'fifa.jpeg',
                'thumbnail_url' => 'fifa.jpeg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Fortnite',
                'developer' => 'Epic Games',
                'release_date' => '2017-07-21',
                'description' => 'Battle royale cartoonish.',
                'category' => 'Battle Royale',
                'brand' => 'Epic Games',
                'digiflazz_id' => 'fortnite',
                'icon_url' => 'fortnite.jpg',
                'thumbnail_url' => 'fortnite.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Honkai Star Rail',
                'developer' => 'miHoYo',
                'release_date' => '2023-04-26',
                'description' => 'RPG turn-based dari miHoYo.',
                'category' => 'RPG',
                'brand' => 'miHoYo',
                'digiflazz_id' => 'hsr',
                'icon_url' => 'hsr.webp',
                'thumbnail_url' => 'hsr.webp',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'League of Legends',
                'developer' => 'Riot Games',
                'release_date' => '2009-10-27',
                'description' => 'MOBA PC populer.',
                'category' => 'MOBA',
                'brand' => 'Riot Games',
                'digiflazz_id' => 'lol',
                'icon_url' => 'lol.jpeg',
                'thumbnail_url' => 'lol.jpeg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Minecraft',
                'developer' => 'Mojang',
                'release_date' => '2011-11-18',
                'description' => 'Game sandbox kreatif.',
                'category' => 'Sandbox',
                'brand' => 'Mojang',
                'digiflazz_id' => 'minecraft',
                'icon_url' => 'minecraft.jpg',
                'thumbnail_url' => 'minecraft.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Pokemon',
                'developer' => 'Nintendo',
                'release_date' => '1996-02-27',
                'description' => 'Game monster collection.',
                'category' => 'RPG',
                'brand' => 'Nintendo',
                'digiflazz_id' => 'pokemon',
                'icon_url' => 'pokemon.jpg',
                'thumbnail_url' => 'pokemon.jpg',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Roblox',
                'developer' => 'Roblox Corporation',
                'release_date' => '2006-09-01',
                'description' => 'Platform game dan kreator.',
                'category' => 'Sandbox',
                'brand' => 'Roblox',
                'digiflazz_id' => 'roblox',
                'icon_url' => 'roblox.webp',
                'thumbnail_url' => 'roblox.webp',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Arena of Valor (ROV)',
                'developer' => 'Garena',
                'release_date' => '2016-10-14',
                'description' => 'MOBA mobile populer di Asia.',
                'category' => 'MOBA',
                'brand' => 'Garena',
                'digiflazz_id' => 'rov',
                'icon_url' => 'rov.png',
                'thumbnail_url' => 'rov.png',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
            [
                'product_name' => 'Wild Rift',
                'developer' => 'Riot Games',
                'release_date' => '2020-10-27',
                'description' => 'League of Legends versi mobile.',
                'category' => 'MOBA',
                'brand' => 'Riot Games',
                'digiflazz_id' => 'wildrift',
                'icon_url' => 'wr.png',
                'thumbnail_url' => 'wr.png',
                'price' => 0,
                'status' => 'active',
                'is_active' => 1,
                'is_popular' => 1,
            ],
        ]);
    }
} 